### ISSUE TITLE
I don’t get notifications when someone replies to my comment

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#147]
I can’t remember if we changed this functionality, but the new reply was on my comment on my own post so something should have definitely come up, right?

I also appear to have got only 3 ‘X replied to a post you have also replied to’ notifications for a different post when I was supposed to get at least 9 (do nested replies count for that notification?)

**Comment by toBeOfUse** [comment]
In the nicest way possible, eliminating the question marks from this kind
of issue is why I wrote all those notification rules in the functional
specification document originally, which are now slightly out of date from
when you added different notifications for threaded comment replies

**Comment by lowercasename** [comment]
I’m onboard with both the tone and the content of that, why are rules so _hard_

**Comment by lowercasename** [comment]
Okay the notifications error appears to be:

```
4|sweet    | ReferenceError: email is not defined
4|sweet    |     at User.findOne.then.user (/home/raphael/sweet/app/notifier.js:51:25)
4|sweet    |     at <anonymous>
4|sweet    |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Here's the whole logfile: https://sweet.sh/error.txt

**Comment by lowercasename** [comment]
Looking into this now

**Comment by lowercasename** [comment]
Actually scrap that, I need to drink a beer and have a rest away from screens!
