### ISSUE TITLE
Some sort of problem with tags?

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#148]
From the logs:

```
4|sweet    | (node:23466) UnhandledPromiseRejectionWarning: CastError: Cast to date failed for value "Invalid Date" at path "lastUpdated" for model "Tag"
4|sweet    |     at new CastError (/home/raphael/sweet/node_modules/mongoose/lib/error/cast.js:29:11)
4|sweet    |     at SchemaDate.cast (/home/raphael/sweet/node_modules/mongoose/lib/schema/date.js:305:11)
4|sweet    |     at SchemaDate.handleSingle (/home/raphael/sweet/node_modules/mongoose/lib/schema/date.js:316:15)
4|sweet    |     at SchemaDate.castForQuery (/home/raphael/sweet/node_modules/mongoose/lib/schema/date.js:347:18)
4|sweet    |     at SchemaDate.SchemaType.castForQueryWrapper (/home/raphael/sweet/node_modules/mongoose/lib/schematype.js:1216:17)
4|sweet    |     at cast (/home/raphael/sweet/node_modules/mongoose/lib/cast.js:288:39)
4|sweet    |     at model.Query.Query.cast (/home/raphael/sweet/node_modules/mongoose/lib/query.js:4340:12)
4|sweet    |     at model.Query.Query._castConditions (/home/raphael/sweet/node_modules/mongoose/lib/query.js:1723:10)
4|sweet    |     at model.Query.<anonymous> (/home/raphael/sweet/node_modules/mongoose/lib/query.js:1750:8)
4|sweet    |     at model.Query._wrappedThunk [as _find] (/home/raphael/sweet/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
4|sweet    |     at process.nextTick (/home/raphael/sweet/node_modules/kareem/index.js:369:33)
4|sweet    |     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
4|sweet    |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
4|sweet    |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

Not sure what this is, still not home

**Comment by toBeOfUse** [comment]
This was happening in the search function, searching for tags, I probably fixed this at some point
